apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
        - name: validator
          image: quay.io/ibaranau/validator:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: validator
spec:
  selector:
    app: validator
  ports:
    - port: 80
      targetPort: 8080
